### ISSUE TITLE
Sentinel appears to be deleting tmp file too early?

### ISSUE THREAD

**Issue by freman** [BlueDragonX/sentinel#1]
sentinel 2014/09/19 09:54:21.764364 [NOTICE] executing watchers
sentinel 2014/09/19 09:54:21.765364 [ERROR]  upstreams failed to render: rename /tmp/sentinel664279573 : no such file or directory
sentinel 2014/09/19 09:54:21.765380 [FATAL]  failed to execute: rename /tmp/sentinel664279573 : no such file or directory

```
etcd:
  uri: http://172.17.42.1:4001/
  prefix: beacon
watchers:
  upstreams:
    watch:
    - lb_appserver/_index
    - lb_static/_index
    context:
    - lb_appserver
    - lb_static
    templates:
    - src: /etc/sentinel/upstreams.tpl
      dst: /opt/nginx/conf/upstreams.conf
    command: /opt/nginx/sbin/nginx -s reload
```
