### ISSUE TITLE
context and templates are *required* when using a command

### ISSUE THREAD

**Issue by anoldguy** [BlueDragonX/sentinel#4]
According to [the Readme](https://github.com/BlueDragonX/sentinel/blame/master/README.md#L11-L12): 

> If no templates are provided to a watcher then the command will always be executed.

Testing this, I do not find this statement to be accurate.  Reading the docs, I would expect to be able to have just a `prefix`, `watch` key, and `command` in a watcher config.  `context` only matters for rendering a template, same for the `templates` config.  However, if I remove context and templates from a watcher config and reduce it to the minimum:

``` yaml
watchers:
  restart:
    prefix: path/to/stuff
    watch:
      - foo/_restart
    command: /path/to/command
```

The command never gets executed, and I get this in the logs:

```
sentinel 2014/11/24 16:20:28.027254 [DEBUG]  key '/path/to/stuff/foo/_restart' changed
sentinel 2014/11/24 16:20:28.027610 [DEBUG]  context: map[]

sentinel 2014/11/24 16:20:28.027864 [INFO]   restart skipped execution
```

If I add back in a context, I get:

```
sentinel 2014/11/24 16:21:52.488368 [DEBUG]  key '/path/to/stuff/foo/_restart' changed
sentinel 2014/11/24 16:21:52.490828 [DEBUG]  get key '/path/to/stuff/foo/_restart': &{/path/to/stuff/foo/_restart Mon Nov 24 16:21:52 UTC 2014 false <nil> 0 [] 46 46}
sentinel 2014/11/24 16:21:52.490856 [DEBUG]  context: map[foo:map[_restart:Mon Nov 24 16:21:52 UTC 2014]]

sentinel 2014/11/24 16:21:52.490866 [INFO]   restart skipped execution
```

If I add back in a context and a template:

``` yaml
watchers:
  restart:
    prefix: path/to/stuff
    watch:
      - foo/_restart
    context:
      - foo/_restart
    templates:
      - src: /etc/sentinel.d/templates/generic.tpl
        dest: /tmp/confirm_restart.txt
```

Then the watcher executes the command as expected:

```
sentinel 2014/11/24 16:24:29.697121 [DEBUG]  key '/path/to/stuff/foo/_restart' changed
sentinel 2014/11/24 16:24:29.704750 [DEBUG]  get key '/path/to/stuff/foo/_restart': &{/path/to/stuff/foo/_restart Mon Nov 24 16:24:29 UTC 2014 false <nil> 0 [] 47 47}
sentinel 2014/11/24 16:24:29.706258 [DEBUG]  context: map[foo:map[_restart:Mon Nov 24 16:24:29 UTC 2014]]

sentinel 2014/11/24 16:24:29.708120 [DEBUG]  template '/etc/sentinel.d/templates/generic.tpl' rendered to '/tmp/confirm_restart.txt'
sentinel 2014/11/24 16:24:29.709947 [DEBUG]  restart calling command
sentinel 2014/11/24 16:24:29.720691 [INFO]   restart executed
```

The command I'm using to update etcd is updating fine, and is just a simple curl:

```
curl -XPUT http://localhost:4001/v2/keys/path/to/stuff/foo/_restart -d value="$(date)"
```

``` json
{
    "action": "set", 
    "node": {
        "createdIndex": 44, 
        "key": "/path/to/stuff/foo/_restart", 
        "modifiedIndex": 44, 
        "value": "Mon Nov 24 16:10:46 UTC 2014"
    }, 
    "prevNode": {
        "createdIndex": 43, 
        "key": "/path/to/stuff/foo/_restart", 
        "modifiedIndex": 43, 
        "value": "Mon Nov 24 16:10:29 UTC 2014"
    }
}
```
